//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.WebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name getCreatorResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCreator", ReplyAction="*")]
        Site.WebService.getCreatorResponse getCreator(Site.WebService.getCreatorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCreator", ReplyAction="*")]
        System.Threading.Tasks.Task<Site.WebService.getCreatorResponse> getCreatorAsync(Site.WebService.getCreatorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCreatorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCreator", Namespace="http://tempuri.org/", Order=0)]
        public Site.WebService.getCreatorRequestBody Body;
        
        public getCreatorRequest() {
        }
        
        public getCreatorRequest(Site.WebService.getCreatorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getCreatorRequestBody {
        
        public getCreatorRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCreatorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCreatorResponse", Namespace="http://tempuri.org/", Order=0)]
        public Site.WebService.getCreatorResponseBody Body;
        
        public getCreatorResponse() {
        }
        
        public getCreatorResponse(Site.WebService.getCreatorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getCreatorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getCreatorResult;
        
        public getCreatorResponseBody() {
        }
        
        public getCreatorResponseBody(string getCreatorResult) {
            this.getCreatorResult = getCreatorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Site.WebService.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Site.WebService.WebServiceSoap>, Site.WebService.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Site.WebService.getCreatorResponse Site.WebService.WebServiceSoap.getCreator(Site.WebService.getCreatorRequest request) {
            return base.Channel.getCreator(request);
        }
        
        public string getCreator() {
            Site.WebService.getCreatorRequest inValue = new Site.WebService.getCreatorRequest();
            inValue.Body = new Site.WebService.getCreatorRequestBody();
            Site.WebService.getCreatorResponse retVal = ((Site.WebService.WebServiceSoap)(this)).getCreator(inValue);
            return retVal.Body.getCreatorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Site.WebService.getCreatorResponse> Site.WebService.WebServiceSoap.getCreatorAsync(Site.WebService.getCreatorRequest request) {
            return base.Channel.getCreatorAsync(request);
        }
        
        public System.Threading.Tasks.Task<Site.WebService.getCreatorResponse> getCreatorAsync() {
            Site.WebService.getCreatorRequest inValue = new Site.WebService.getCreatorRequest();
            inValue.Body = new Site.WebService.getCreatorRequestBody();
            return ((Site.WebService.WebServiceSoap)(this)).getCreatorAsync(inValue);
        }
    }
}
